### ISSUE TITLE
You are copying

### ISSUE THREAD

**Issue by Meiyim** [llSourcell/capsule_networks#2]
You are copying from other people's work: https://github.com/naturomics/CapsNet-Tensorflow
This is not cool, dude.

**Comment by bauerzhou** [comment]
@llSourcell you should declare where your code from ....as i know, you copy from https://github.com/naturomics/CapsNet-Tensorflow

**Comment by llSourcell** [comment]
i gave them credit in the README, never claimed it to by mine
